version: '3.5'

services: 
    kurkkufront:
      build: ./ml-kurkkumopo-frontend
      image: ml-kurkkumopo-frontend
      ports: 
        - 3000:3000
    kurkkuback:
      build: ./ml-kurkkumopo-backend
      image: ml-kurkkumopo-backend
      ports:
        - 5000:5000
      volumes:
        - models:/src/model
    kurkkutraining:
      build: ./ml-kurkkumopo-training
      image: ml-kurkkumopo-training
      volumes: 
        - images:/src/imgs
        - models:/src/model

volumes:
    models:
    images:
